//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExamAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestFile
    {
        public int FileId { get; set; }
        public string Path { get; set; }
        public Nullable<int> Level { get; set; }
        public Nullable<int> SubjectId { get; set; }
    
        public virtual TestSubject TestSubject { get; set; }
    }
}
