//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExamAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestSubject
    {
        public TestSubject()
        {
            this.TestFiles = new HashSet<TestFile>();
        }
    
        public int SubjectId { get; set; }
        public string Subject { get; set; }
        public Nullable<int> TotalMark { get; set; }
        public Nullable<int> PassingMark { get; set; }
        public Nullable<int> ExamDuration { get; set; }
        public string TStatus { get; set; }
    
        public virtual ICollection<TestFile> TestFiles { get; set; }
    }
}
